In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
import numpy as np

In [3]:
iris=datasets.load_iris()
x=iris.data
print(x)
y=iris.target
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=25)

In [9]:
reg=LinearRegression()
reg.fit(x_train,y_train)
y_predict=reg.predict(x_test)
print("-----------test_class-------------\n",y_test)
print("-----------predict_class-----------\n",y_predict)
print("coeffiecient;",reg.coef_)
print("ntercept:",reg.intercept_)

-----------test_class-------------
 [0 1 1 1 2 1 2 0 1 1 0 0 0 2 0 1 2 2 1 1 1 1 1 0 0 2 1 2 2 0 1 2 2 0 2 1 1
 0]
-----------predict_class-----------
 [-0.07746488  1.43445753  1.60275603  1.39107053  1.93516492  1.18864824
  1.61495206 -0.00581977  0.94823105  0.91795494  0.0630903   0.04863727
  0.1117134   1.46163977  0.0468488   1.19116265  1.73068725  1.8234657
  1.07596064  1.21793597  0.87295889  1.18029989  1.39184274 -0.03259309
 -0.00821941  2.04877625  1.0385357   1.97881819  2.00835948  0.09575718
  1.33186047  1.83038885  2.02418256 -0.06782952  1.97258986  1.33962937
  1.37392369 -0.02172083]
coeffiecient; [-0.10311185 -0.05493508  0.21831386  0.62446566]
ntercept: 0.21496346623668483


In [11]:
err=mean_squared_error(y_test,y_predict)
print(err)
rsc=r2_score(y_predict,y_test)
print(rsc)

0.053426441361305116
0.9008192710979503
