In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
iris=datasets.load_iris()
x=iris.data
y=iris.target

In [2]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [3]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [11]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [12]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)
print("___ytest___\n",ytest)

___ytest___
 [0 2 2 2 0 2 0 1 2 1 0 2 1 1 1 0 1 2 1 0 0 0 0 1 2 1 1 0 2 2 2 2 0 1 1 1 0
 0]


In [13]:
sl_reg=LinearRegression()
sl_reg.fit(xtrain,ytrain)
y_predict=sl_reg.predict(xtest)
print("----------test class--------\n",ytest)
print("----------predict class-------\n",y_predict)

----------test class--------
 [0 2 2 2 0 2 0 1 2 1 0 2 1 1 1 0 1 2 1 0 0 0 0 1 2 1 1 0 2 2 2 2 0 1 1 1 0
 0]
----------predict class-------
 [-0.11866363  1.83125437  1.75412682  1.6809865  -0.16309975  1.83619073
  0.00682948  0.83386742  2.0062371   1.1477845   0.01862469  1.46378376
  1.6040939   1.49240322  1.27486401 -0.08174951  1.1213058   1.72056228
  1.20684554 -0.07067605 -0.02288164  0.00755123 -0.06272554  1.15706968
  2.04581288  1.42011923  1.19870187  0.03763994  1.56004409  1.78832902
  1.60180215  2.13064727 -0.12192117  1.0621189   1.1738856   1.16642215
 -0.02460262 -0.10580187]


In [14]:
mse=mean_squared_error(ytest,y_predict)
print('mean squared error:',mse)

mean squared error: 0.05728828492393281


In [15]:
r2=r2_score(ytest,y_predict)
print('r2:',r2)

r2: 0.9128300490725406


In [16]:
print('coefficient:',sl_reg.coef_)
print('intercept:',sl_reg.intercept_)

coefficient: [-0.13239347  0.01082941  0.26352828  0.56315679]
intercept: 0.07194326025432984
